language: java

services:
  - docker

before_install:
  - docker build -t sourabh51/springbootapp:1.0 .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sourabh51/springbootapp:1.0
  - docker ps -a
  - docker run sourabh51/springbootapp:1.0 /bin/sh -c "cd /root/springbootapp; bundle exec rake test"
  
script:
  - bundle exec rake test
  
notifications:
  email: sourabh.h51@gmail.com
