dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t springbootapp .
      - docker images
      - docker tag springbootapp $DOCKER_USERNAME/springbootapp
      - docker push $DOCKER_USERNAME/springbootapp
      
    - stage: test
      script:
      - docker run $DOCKER_USERNAME/springbootapp echo "This is a sample text" > hello.txt
      - docker ps -a 
